name: charge_ev
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.11
  google_maps_flutter: ^2.1.3
  geoflutterfire: ^3.0.3
  firebase_core: ^1.14.0
  geolocator: ^8.2.0
  provider: ^6.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
