// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Q_qNS9TA8mlyqXPtryMO6saURlRVIO4',
    appId: '1:414893524286:web:172b9430faf3f94bc7986f',
    messagingSenderId: '414893524286',
    projectId: 'epoweripi-charge-ev',
    authDomain: 'epoweripi-charge-ev.firebaseapp.com',
    storageBucket: 'epoweripi-charge-ev.appspot.com',
    measurementId: 'G-CB6HGSP0K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6O3uzSCnBZcN2XoAj-_oVAQNpPE8CLwM',
    appId: '1:414893524286:android:ca5340501f16e225c7986f',
    messagingSenderId: '414893524286',
    projectId: 'epoweripi-charge-ev',
    storageBucket: 'epoweripi-charge-ev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0JpbK2gZGaxCc89TaEe_mi7Q27UaQO8E',
    appId: '1:414893524286:ios:086efa73aba1fce4c7986f',
    messagingSenderId: '414893524286',
    projectId: 'epoweripi-charge-ev',
    storageBucket: 'epoweripi-charge-ev.appspot.com',
    iosClientId: '414893524286-ubup4smflbnea9cs60p9fa48cgutk97d.apps.googleusercontent.com',
    iosBundleId: 'com.epoweripi.chargeev',
  );
}
